version: '2'

services:
  mysql:
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: bigsecret
  php:
    build: ./php/
    volumes:
      - ./src:/var/www/html
      - /home/user/.ssh:/home/user/.ssh
    links:
      - my:my
    restart: unless-stopped
  nginx:
    image: nginx:1.13.9
    networks:
      default:
        aliases:
          - site.local
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - php
    links:
      - php:php-site
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  redis:
    image: redis
